-- Create GameArena user in XEPDB1
SET PAGESIZE 0 FEEDBACK ON VERIFY OFF ECHO ON

-- Drop user if exists
BEGIN
    EXECUTE IMMEDIATE 'DROP USER gamearena CASCADE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Create user
CREATE USER gamearena IDENTIFIED BY gamearena123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- Grant permissions
GRANT CONNECT, RESOURCE TO gamearena;
GRANT CREATE SESSION TO gamearena;
GRANT CREATE TABLE TO gamearena;
GRANT CREATE VIEW TO gamearena;
GRANT CREATE PROCEDURE TO gamearena;
GRANT CREATE SEQUENCE TO gamearena;
GRANT CREATE TRIGGER TO gamearena;
GRANT CREATE ANY PROCEDURE TO gamearena;
GRANT ALTER ANY PROCEDURE TO gamearena;
GRANT DROP ANY PROCEDURE TO gamearena;

PROMPT '=== User GAMEARENA created successfully! ==='
EXIT;
